export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ALL_TRENDING_MOVIES = 'GET_ALL_TRENDING_MOVIES';
export const GET_ALL_TRENDING_TVSHOWS = 'GET_ALL_TRENDING_TVSHOWS';
export const GET_ALL_TRENDING_PEOPLE = 'GET_ALL_TRENDING_PEOPLE';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const GET_MOVIES_BY_ID = 'GET_MOVIES_BY_ID';
export const GET_PERSON_BY_ID = 'GET_PERSON_BY_ID';
export const GET_POPULAR_PEOPLE = 'GET_POPULAR_PEOPLE';
export const GET_MOVIES_NOW_PLAYING = 'GET_MOVIES_NOW_PLAYING';
export const GET_MOVIES_POPULAR = 'GET_MOVIES_POPULAR';
export const GET_MOVIES_TOP_RATED = 'GET_MOVIES_TOP_RATED';
export const GET_MOVIES_UPCOMING = 'GET_MOVIES_UPCOMING';
export const GET_TVSHOW_BY_ID = 'GET_TVSHOW_BY_ID';
export const GET_TVSHOWS_POPULAR = 'GET_TVSHOW_POPULAR';
export const GET_TVSHOWS_AIRING_TODAY = 'GET_TVSHOWS_AIRING_TODAY';
export const GET_TVSHOWS_ON_TV = 'GET_TVSHOWS_ON_TV';
export const GET_TVSHOWS_TOP_RATED = 'GET_TVSHOWS_TOP_RATED';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const GET_FAVORITES = 'GET_FAVORITES';
export const ADD_FAVORITE_FAIL = 'ADD_FAVORITE_FAIL';
export const GET_FAVORITE_FAIL = 'GET_FAVORITE_FAIL';
export const DELETE_FAVORITE_FAIL = 'DELETE_FAVORITE_FAIL';



