export const GET_ALL_TRENDING_MOVIES = 'GET_ALL_TRENDING_MOVIES';
export const GET_ALL_TRENDING_TVSHOWS = 'GET_ALL_TRENDING_TVSHOWS';
export const GET_ALL_TRENDING_PEOPLE = 'GET_ALL_TRENDING_PEOPLE';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const GET_MOVIES_BY_ID = 'GET_MOVIES_BY_ID';
export const GET_TVSHOW_BY_ID = 'GET_TVSHOW_BY_ID';
export const GET_PERSON_BY_ID = 'GET_PERSON_BY_ID';
export const GET_MOVIES_NOW_PLAYING = 'GET_MOVIES_NOW_PLAYING';
export const GET_MOVIES_POPULAR = 'GET_MOVIES_POPULAR';
export const GET_MOVIES_TOP_RATED = 'GET_MOVIES_TOP_RATED';
export const GET_MOVIES_UPCOMING = 'GET_MOVIES_UPCOMING';


