export const GET_ALL_TRENDING_MOVIES = 'GET_ALL_TRENDING_MOVIES';
export const GET_ALL_TRENDING_TVSHOWS = 'GET_ALL_TRENDING_TVSHOWS';
export const GET_ALL_TRENDING_PEOPLE = 'GET_ALL_TRENDING_PEOPLE';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const GET_MOVIES_BY_ID = 'GET_MOVIES_BY_ID';
export const GET_TVSHOW_BY_ID = 'GET_TVSHOW_BY_ID';


